### ISSUE TITLE
DownloadDocuments#package_contents is not idempotent

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#116]
If `GetDownloadFilesJob` is run more than once (e.g., due to failure), subsequent attempts will _append_ to the zip file, resulting in duplicate entry exceptions, and another job failure.

```
Failure! Retry 5 in 808 seconds
fail: 110.742 sec
{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"GetDownloadFilesJob","queue":"default","args":[{"job_class":"GetDownloadFilesJob","job_id":"5cf30932-4423-4c61-9a
19-76b1770c1af4","queue_name":"default","arguments":[{"_aj_globalid":"gid://caseflow-efolder/Download/549"}],"locale":"en"}],"retry":true,"jid":"031c92a78e64435f4e5f9403","created_at":1467
311480.3596063,"enqueued_at":1467312629.7451968,"error_message":"add failed. Entry 0-form8-xxxx.pdf already exists","error_class":"Zip::EntryExistsError","failed_at":1467311576.3110192,
"retry_count":5,"retried_at":1467312740.487074}
Zip::EntryExistsError: add failed. Entry 0-form8-xxxx.pdf already exists
/opt/efolder-express/src/vendor/bundle/ruby/2.2.0/gems/rubyzip-1.2.0/lib/zip/file.rb:396:in `check_entry_exists'
/opt/efolder-express/src/vendor/bundle/ruby/2.2.0/gems/rubyzip-1.2.0/lib/zip/file.rb:270:in `add'
/opt/efolder-express/src/app/services/download_documents.rb:90:in `block (2 levels) in package_contents'
/opt/efolder-express/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:132:in `each'
```

**Comment by orischwartz** [comment]
Closed via https://github.com/department-of-veterans-affairs/caseflow-efolder/commit/f34b433768174f25ddaad408d2cb22b647ddc386#diff-a4389ce312191ae68bc9183bd4c4fae5R99
