### ISSUE TITLE
Upgrade httpclient gem version to remove the warning messages.

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#361]
The version of `httpclient` that Efolder is using is generating a lot of warning messages. These messages are polluting Cloudwatch and makes debugging painful.

We just need to upgrade `httpclient` to a newer version. (See https://github.com/nahi/httpclient/pull/287)

Here's an example of the noise in our logs.
```
opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:983:in `read_body_chunked': Object#timeout is deprecated, use Timeout.timeout instead.
```

**Comment by kierachell** [comment]
**PASSED**
eFolder stress test is passing as far as the `httpclient` is concerned.
