### ISSUE TITLE
Efolder OmniAuth::Strategies::SAML::ValidationError

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-efolder#382]
Error 500 is observed in Efolder.

The error was attempted to be sent to Sentry, but Sentry security group was configured incorrectly (now fixed).

The VA username and email address are obfuscated in the log.

```
[VBAUSERNAME firstname.lastname@va.gov 376] Started GET "/auth/saml_callback" for 172.30.86.133 at 2017-02-09 12:00:03 -0500
I, [2017-02-09T12:00:03.719976 #2693]  INFO -- omniauth: (samlva) Callback phase initiated.
E, [2017-02-09T12:00:03.720242 #2693] ERROR -- omniauth: (samlva) Authentication failure! invalid_ticket: OmniAuth::Strategies::SAML::ValidationError, SAML response missing
I, [2017-02-09T12:00:03.732732 #2693]  INFO -- sentry: ** [Raven] Sending event ea6ac3afef3e4494abfc56454b73fdbb to Sentry
E, [2017-02-09T12:00:05.031711 #2693] ERROR -- sentry: ** [Raven] Unable to record event with remote Sentry server (NoMethodError - undefined method `[]' for nil:NilClass)
E, [2017-02-09T12:00:05.031838 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.3.0/lib/raven/transports/http.rb:32:in `rescue in send_event'
E, [2017-02-09T12:00:05.031867 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.3.0/lib/raven/transports/http.rb:18:in `send_event'
E, [2017-02-09T12:00:05.031887 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.3.0/lib/raven/client.rb:40:in `send_event'
E, [2017-02-09T12:00:05.031906 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.3.0/lib/raven/instance.rb:81:in `send_event'
E, [2017-02-09T12:00:05.031924 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.3.0/lib/raven/instance.rb:126:in `capture_type'
E, [2017-02-09T12:00:05.031942 #2693] ERROR -- sentry: ** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/forwardable.rb:184:in `capture_type'
E, [2017-02-09T12:00:05.031960 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.3.0/lib/raven/integrations/rack.rb:28:in `capture_type'
E, [2017-02-09T12:00:05.031983 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.3.0/lib/raven/integrations/rails/overrides/debug_exceptions_catcher.rb:8:in `render_exception'
E, [2017-02-09T12:00:05.032001 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:27:in `rescue in call'
E, [2017-02-09T12:00:05.032020 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
E, [2017-02-09T12:00:05.032059 #2693] ERROR -- sentry: ** [Raven] /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
E, [2017-02-09T12:00:05.032099 #2693] ERROR -- sentry: ** [Raven] Failed to submit event: OmniAuth::Strategies::SAML::ValidationError: SAML response missing
[VBAUSERNAME firstname.lastname@va.gov 376] 
OmniAuth::Strategies::SAML::ValidationError (SAML response missing):
  app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by aroltsch** [comment]
@askldjd is it still a problem?

**Comment by aroltsch** [comment]
duplicate of #491
