### ISSUE TITLE
Expired cached downloads not retireve properly

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow-efolder#408]
It seems like some kind of configuration between eFolder and VBMS and our cache is not working in `uat` at this time; a simple `listDocuments` query is either never sent or never received for specific VBMS IDs. Downloads _are_ possible in `preprod`, but most of our integration tests do and will run in `uat` and `preprod` lacks data to nail down this bug.

Most IDs are fine to work; but sometimes (maybe for an expired download/search) if you search for a specific ID (ask me) you'll just end up with an endless spinner and following logs:

```[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ] Started POST "/downloads" for 172.30.67.144 at 2017-03-04 13:56:59 -0500
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ] Processing by DownloadsController#create as HTML
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"KAo71RwEEy6h4p1Fh/itmnyhJuG7ZLzbY9NmjiKeYTqwfL8rxE/ToWMHdH9aRQeealjfAN0EQUyP3NAqkHCBFw==", "file_number"=>"*****"}
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ]   [1m[36mUser Load (0.9ms)[0m  [1mSELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1[0m  [["css_id", "CASEFLOW1"], ["station_id", "283"]]
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ]   [1m[35m (0.6ms)[0m  BEGIN
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ]   [1m[36m (0.5ms)[0m  [1mCOMMIT[0m
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ]   [1m[35mDownload Load (1.0ms)[0m  SELECT  "downloads".* FROM "downloads" WHERE ("downloads"."created_at" BETWEEN '2017-03-01 18:56:59.186828' AND '2017-03-04 18:56:59.186850') AND "downloads"."file_number" = $1 AND "downloads"."user_id" = 3 AND ("downloads"."status" NOT IN (1, 7))  ORDER BY "downloads"."id" ASC LIMIT 1  [["file_number", "*****"]]
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ]   [1m[36m (0.7ms)[0m  [1mBEGIN[0m
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ]   [1m[35mSQL (1.1ms)[0m  INSERT INTO "searches" ("user_id", "file_number", "download_id", "status", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["user_id", 3], ["file_number", "******"], ["download_id", 762], ["status", 1], ["created_at", "2017-03-04 18:56:59.191092"]]
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ]   [1m[36m (1.7ms)[0m  [1mCOMMIT[0m
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ] Redirected to https://efolder.cf.uat.ds.va.gov/downloads/762
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ] Completed 302 Found in 13ms (ActiveRecord: 6.6ms)
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ] Started GET "/assets/uswds/sourcesanspro-regular-webfont.woff2" for 172.30.67.144 at 2017-03-04 13:56:59 -0500
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ] 
ActionController::RoutingError (No route matches [GET] "/assets/uswds/sourcesanspro-regular-webfont.woff2"):
  app/middleware/metrics_auth.rb:10:in `call'

[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ] Started GET "/assets/uswds/sourcesanspro-regular-webfont.ttf" for 172.30.67.144 at 2017-03-04 13:56:59 -0500
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:56:59 -0500] [CASEFLOW1 ] 
ActionController::RoutingError (No route matches [GET] "/assets/uswds/sourcesanspro-regular-webfont.ttf"):
  app/middleware/metrics_auth.rb:10:in `call'

[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:01 -0500] [CASEFLOW1 ] Started GET "/downloads/762" for 172.30.67.144 at 2017-03-04 13:57:01 -0500
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:01 -0500] [CASEFLOW1 ] Processing by DownloadsController#show as JSON
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:01 -0500] [CASEFLOW1 ]   Parameters: {"id"=>"762"}
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:01 -0500] [CASEFLOW1 ]   [1m[35mUser Load (0.7ms)[0m  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1  [["css_id", "CASEFLOW1"], ["station_id", "283"]]
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:01 -0500] [CASEFLOW1 ]   [1m[36m (0.5ms)[0m  [1mBEGIN[0m
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:01 -0500] [CASEFLOW1 ]   [1m[35m (0.5ms)[0m  COMMIT
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:01 -0500] [CASEFLOW1 ]   [1m[36mDownload Load (0.7ms)[0m  [1mSELECT  "downloads".* FROM "downloads" WHERE ("downloads"."created_at" BETWEEN '2017-03-01 18:57:01.540403' AND '2017-03-04 18:57:01.540426') AND "downloads"."user_id" = 3 AND "downloads"."id" = $1 LIMIT 1[0m  [["id", 762]]
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:01 -0500] [CASEFLOW1 ] Completed 200 OK in 7ms (Views: 0.1ms | ActiveRecord: 2.4ms)
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:03 -0500] [CASEFLOW1 ] Started GET "/downloads/762" for 172.30.67.144 at 2017-03-04 13:57:03 -0500
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:03 -0500] [CASEFLOW1 ] Processing by DownloadsController#show as JSON
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:03 -0500] [CASEFLOW1 ]   Parameters: {"id"=>"762"}
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:03 -0500] [CASEFLOW1 ]   [1m[35mUser Load (1.2ms)[0m  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1  [["css_id", "CASEFLOW1"], ["station_id", "283"]]
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:03 -0500] [CASEFLOW1 ]   [1m[36m (0.6ms)[0m  [1mBEGIN[0m
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:03 -0500] [CASEFLOW1 ]   [1m[35m (0.5ms)[0m  COMMIT
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:03 -0500] [CASEFLOW1 ]   [1m[36mDownload Load (0.7ms)[0m  [1mSELECT  "downloads".* FROM "downloads" WHERE ("downloads"."created_at" BETWEEN '2017-03-01 18:57:03.545728' AND '2017-03-04 18:57:03.545751') AND "downloads"."user_id" = 3 AND "downloads"."id" = $1 LIMIT 1[0m  [["id", 762]]
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:03 -0500] [CASEFLOW1 ] Completed 200 OK in 8ms (Views: 0.1ms | ActiveRecord: 2.9ms)
[efolder.cf.uat.ds.va.gov] [172.30.66.115] [2017-03-04 13:57:05 -0500] [CASEFLOW1 ] Started GET "/downloads/762" for 172.30.67.144 at 2017-03-04 13:57:05 -0500
```

The last 10 lines of the log enter into an endless loop (repeats every 2 seconds).

This started this past Thursday and only happens to specific IDs - they will just spin forever.

## Steps 2:

1. Login to eFolder in `uat`

1. Search for a vet with 3+ documents

1. Watch the spinner for 4+ hours with no results

1. Ask self why you wasted 4+ hours on this.

## Notes
This could be related to this https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/426 and this https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/356

**Comment by shanear** [comment]
> # Steps 2: 

> 1. Login to eFolder in `uat`

> 1. Search for a vet 3+ documents

> 1. Get *Uh Oh* message

> 1. Go back

> 1. Search for same ID again

> 1. Observe that it _did_ work

This is a dup of #375. Removing it from this bug

**Comment by kierachell** [comment]
I am seeing that `fetching_manifest?` is being requested of a download - but it is not being set anywhere to anything other than 0. Does this mean that any evaluation of it is falsy?

**Comment by aroltsch** [comment]
@kierachell , `fetching_manifest` is a download status. To hit pry in the job, try restarting sidekiq.

**Comment by aroltsch** [comment]
Shane'c comment refers to issue #375 ,

**Comment by aroltsch** [comment]
Closing this until another case comes up.
