### ISSUE TITLE
Download.bgs_service is intermittently null on Sidekiq jobs

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-efolder#577]
This appears to have started sometime after the eFolder API launched.

<img width="826" alt="screen shot 2017-08-04 at 10 11 30 am" src="https://user-images.githubusercontent.com/1596259/28972601-4fa9969c-78fe-11e7-9fbc-fbc4fb8fc785.png">

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/325/events/6154/

**Comment by kierachell** [comment]
### From the console:
```
Download.all.sample.fetch_veteran_info
  Download Load (3.5ms)  SELECT "downloads".* FROM "downloads"
[2017-08-04 18:18:41 -0400]   Download Load (3.5ms)  SELECT "downloads".* FROM "downloads"
=> nil
irb(main):048:0> Download.all.sample.fetch_veteran_info
  Download Load (3.2ms)  SELECT "downloads".* FROM "downloads"
[2017-08-04 18:18:43 -0400]   Download Load (3.2ms)  SELECT "downloads".* FROM "downloads"
NoMethodError: undefined method `fetch_veteran_info' for nil:NilClass
        from /opt/efolder-express/src/app/models/download.rb:71:in `fetch_veteran_info'
        from (irb):48
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

**Comment by kierachell** [comment]
## Side effect?:
<img width="1115" alt="screen shot 2017-08-04 at 6 36 56 pm" src="https://user-images.githubusercontent.com/18075411/28989554-07f2aee2-7944-11e7-818d-c4f4c884b73d.png">
https://sentry.uat.ds.va.gov/sentry/efolder-uat-u4/issues/367/
```
def fetch_from_s3(document)
    # if the file exists on the filesystem, skip
    return if File.exist?(document.filepath)
```
nil to string?

**Comment by kierachell** [comment]
## You guys opened a can of worms:

Deserialization? What?
https://sentry.uat.ds.va.gov/sentry/efolder-uat-u4/issues/369/

**Comment by kierachell** [comment]
**PASSED**

Resolved now
