### ISSUE TITLE
handle nil received_to date (empty document content)?

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#67]
https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/vendor/gems/connect_vbms/src/vbms/responses/document_with_content.rb#L13

@shanear  is this the empty document response or something else? 

```
E, [2016-05-27T16:15:45.728000 #20231] ERROR -- : [ActiveJob] [GetDownloadFilesJob] [baa60d81-b959-4ae1-987f-8b52f3b88038] undefined method `content' for nil:NilClass
/opt/efolder-express/src/vendor/gems/connect_vbms/src/vbms/responses/document_with_content.rb:13:in `create_from_xml'
/opt/efolder-express/src/vendor/gems/connect_vbms/src/vbms/requests/fetch_document_by_id.rb:29:in `handle_response'
/opt/efolder-express/src/vendor/gems/connect_vbms/src/vbms/client.rb:223:in `process_response'
/opt/efolder-express/src/vendor/gems/connect_vbms/src/vbms/client.rb:109:in `send_request'
/opt/efolder-express/src/app/services/vbms_service.rb:19:in `fetch_document_file'
/opt/efolder-express/src/app/services/download_documents.rb:27:in `block in download_contents'
org/jruby/RubyArray.java:1560:in `each'
```

**Comment by orischwartz** [comment]
Awaiting response from VBMS on whether this is something we should account for.

**Comment by shanear** [comment]
Per Clayton, this is a defect, and is properly throwing an error.
