### ISSUE TITLE
assets precompile fails after merging #83

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#84]
```bash
$ bin/rake assets:precompile
rake aborted!
SyntaxError: /opt/efolder-express/src/config/environments/production.rb:79: syntax error, unexpected '='
  config.s3_enabled? = true
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:1:in `block in (root)'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:598:in `block in Engine'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:597:in `Engine'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `block in run'
```

**Comment by orischwartz** [comment]
See #83 -- the attribute is `s3_enabled`, not `s3_enabled?`
