### ISSUE TITLE
s3 storage fails in production

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#86]
```
2016-06-06T18:19:58.126Z 2508 TID-wrc WARN: {"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"GetDownloadFilesJob","queue":"default","args":[
{"job_class":"GetDownloadFilesJob","job_id":"530b6238-6023-4b52-9b50-48ef1040e63a","queue_name":"default","arguments":[{"_aj_globalid":"gid://caseflow-efolder/Downloa
d/2"}],"locale":"en"}],"retry":true,"jid":"3d69d2b63639781f00858af0","created_at":1465237187.252,"enqueued_at":1465237187.252,"error_message":"undefined method `put_o
bject' for nil:NilClass","error_class":"NoMethodError","failed_at":1465237198.1,"retry_count":0}
2016-06-06T18:19:58.126Z 2508 TID-wrc WARN: NoMethodError: undefined method `put_object' for nil:NilClass
2016-06-06T18:19:58.126Z 2508 TID-wrc WARN: /opt/efolder-express/src/app/services/s3_service.rb:10:in `store_file'
/opt/efolder-express/src/app/services/download_documents.rb:30:in `block in download_contents'
org/jruby/RubyArray.java:1560:in `each'
org/jruby/RubyEnumerable.java:1016:in `each_with_index'
org/jruby/RubyKernel.java:1822:in `public_send'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:132:in `method_missing'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:99:in `method_missing'
/opt/efolder-express/src/app/services/download_documents.rb:26:in `download_contents'
/opt/efolder-express/src/app/jobs/get_download_files_job.rb:6:in `perform'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activejob-4.2.5.2/lib/active_job/execution.rb:32:in `block in perform_now'
org/jruby/RubyProc.java:318:in `call'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block in compile'
org/jruby/RubyProc.java:318:in `call'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:498:in `block in around'
org/jruby/RubyProc.java:318:in `call'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:343:in `block in simple'
```

**Comment by orischwartz** [comment]
Bucket name was missing from worker env. Closed in https://github.com/department-of-veterans-affairs/appeals-deployment/commit/e0e18c108e4080dc57928dae6a1725470a4ec4a5
