### ISSUE TITLE
undefined method put_object

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#87]
```
2016-06-08T15:24:37.599Z 2563 TID-x5e WARN: {"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"GetDownloadFilesJob","queue":"default","args":[{"job_class":"GetDownloadFilesJob","job_id":"d1420fd2-bb3e-470b-bb48-fb18e4ffd7dd","queue_name":"default","arguments":[{"_aj_globalid":"gid://caseflow-efolder/Download/8"}],"locale":"en"}],"retry":true,"jid":"42c7a0bee3ab6db644a2ed84","created_at":1465394277.789,"enqueued_at":1465399475.606,"error_message":"undefined method `put_object' for nil:NilClass","error_class":"NoMethodError","failed_at":1465394281.584,"retry_count":8,"retried_at":1465399477.597}
2016-06-08T15:24:37.599Z 2563 TID-x5e WARN: NoMethodError: undefined method `put_object' for nil:NilClass
2016-06-08T15:24:37.600Z 2563 TID-x5e WARN: /opt/efolder-express/src/app/services/s3_service.rb:10:in `store_file'
/opt/efolder-express/src/app/services/download_documents.rb:30:in `block in download_contents'
org/jruby/RubyArray.java:1560:in `each'
org/jruby/RubyEnumerable.java:1016:in `each_with_index'
org/jruby/RubyKernel.java:1822:in `public_send'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:132:in `method_missing'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:99:in `method_missing'
/opt/efolder-express/src/app/services/download_documents.rb:26:in `download_contents'
```

**Comment by orischwartz** [comment]
Duplicate of #86, deployed image was outdated.
