### ISSUE TITLE
Duplicate entries encountered when zipping contents for download

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#94]
```
2016-06-08T23:59:33.898Z 2585 TID-2abi WARN: {"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"GetDownloadFilesJob","queue":"default","args":[{"job_class":"GetD
ownloadFilesJob","job_id":"27ca14b5-59f1-4c29-ba19-4a03958e16d5","queue_name":"default","arguments":[{"_aj_globalid":"gid://caseflow-efolder/Download/21"}],"locale":"en"}],"retry":true,
"jid":"7bcecd728e2c063c5aed8899","created_at":1465427607.247,"enqueued_at":1465429838.326,"error_message":"add failed. Entry cdfa639c-7ee5-455b-8d07-fac13c486186-soc.pdf already exists"
,"error_class":"Zip::EntryExistsError","failed_at":1465428110.871,"retry_count":4,"retried_at":1465430373.896}
2016-06-08T23:59:33.898Z 2585 TID-2abi WARN: Zip::EntryExistsError: add failed. Entry cdfa639c-7ee5-455b-8d07-fac13c486186-soc.pdf already exists
2016-06-08T23:59:33.899Z 2585 TID-2abi WARN: /opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/rubyzip-1.2.0/lib/zip/file.rb:397:in `check_entry_exists'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/rubyzip-1.2.0/lib/zip/file.rb:270:in `add'
/opt/efolder-express/src/app/services/download_documents.rb:86:in `block in package_contents'
org/jruby/RubyArray.java:1560:in `each'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/relation/delegation.rb:46:in `each'
/opt/efolder-express/src/app/services/download_documents.rb:84:in `block in package_contents'
```

**Comment by orischwartz** [comment]
Zip entry isn't being prefixed with unique document id

https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/31f801f8a24ccec8ed8dd646b631562f5c45fd57/app/models/document.rb#L5
