### ISSUE TITLE
Consider HTTP timeouts greater than 60 seconds for connect_vbms

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-efolder#99]
```
E, [2016-06-10T10:20:28.232000 #21116] ERROR -- : execution expired
org/jruby/ext/openssl/SSLSocket.java:731:in `sysread'
/opt/efolder-express/.rbenv/versions/jruby-9.0.3.0/lib/ruby/stdlib/jopenssl22/openssl/buffering.rb:60:in `fill_rbuff'
/opt/efolder-express/.rbenv/versions/jruby-9.0.3.0/lib/ruby/stdlib/jopenssl22/openssl/buffering.rb:207:in `gets'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:356:in `gets'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:876:in `block in parse_header'
org/jruby/ext/timeout/Timeout.java:147:in `timeout'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:855:in `read_header'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:662:in `get_header'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1247:in `do_get_header'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1194:in `do_get_block'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
/opt/efolder-express/src/vendor/bundle/jruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:725:in `post'
/opt/efolder-express/src/vendor/gems/connect_vbms/src/vbms/client.rb:87:in `send_request'
/opt/efolder-express/src/app/services/vbms_service.rb:9:in `fetch_documents_for'
/opt/efolder-express/src/app/jobs/get_download_manifest_job.rb:5:in `perform'
```

**Comment by KHarshawat** [comment]
Should trigger an alert that VBMS is slow.

**Comment by shanear** [comment]
@orischwartz lets bump up the timeouts

@KHarshawat we already measure the speed of VBMS. If it being slow becomes a bigger problem, we can address that with them.

**Comment by shanear** [comment]
This issue looks like it isn't needed anymore (via @orischwartz). Closing.
